### ISSUE TITLE
Latest version is detected as malware by multiple antiviruses

### ISSUE THREAD

**Issue by icup321** [darealshinji/sonic-4-launcher#1]
The latest release (r3) is detected by several antiviruses including Windows Defender which automatically removes it: https://www.virustotal.com/gui/file/706703d1f4d8f35376886d988511658e7369a41183a4609138f6514550a0987d/detection

Is there any specific reason for this happening, I know you changed the code to add 'memset' but what exactly is the point of adding that if it just gets flagged as malware? I wanted to add this launcher to PCGamingWiki as an alternative to installing Java, but I can't do it unless this issue is addressed/explained.

**Comment by icup321** [comment]
A friend of mine compiled the launcher on Linux using "g++-mingw-w64-i686" and the executable seems to come up much cleaner in VirusTotal and works just fine: https://www.virustotal.com/gui/file/dd228dcdbea6aaf2a76f385d04a049eed65a4e6cbafae9f7477ec86c169f7726/detection

I will probably recommend people using this one since the other one will not work by default due to Windows flagging it as malware.
[SonicLauncher.zip](https://github.com/darealshinji/sonic-4-launcher/files/4500883/SonicLauncher.zip)

**Comment by darealshinji** [comment]
I thought using `memset()` was "smarter" than using `SecureZeroMemory()` but I can simply revert it. I really don't see how using `memset()` turns it into malware, but okay...

PS: Honestly, I really don't know why AntiVirus software is making so much false positives when they try to analyze binaries made with Mingw.

**Comment by icup321** [comment]
My friend just recompiled the latest source code as well as the previous commit that used memset and both of the executables came out the same on VirusTotal, so I think the real issue here was that the way you compiled r3 was probably done in a way Windows didn't like and flagged it for some reason, it's strange, I think I'll just close this issue, but thanks for responding. I have another issue I'd like to address soon anyway.

**Comment by darealshinji** [comment]
I have compiled it again and I get 5 warnings for the Visual Studio build and 2 warnings for the GCC build:
https://www.virustotal.com/gui/file/2dc0dc40afb3df2e23c36969699a1379f2a3bffed46a63757c7ac4272334a475/detection
https://www.virustotal.com/gui/file/7fbe125aa973842f722140eed90dc25766f2ac8eb76e5b97ad9b73d052032524/detection

I also see that the binary made by your friend is quite bigger than the one I created. Can your friend tell you how they created the binary so I could include those changes here? That would be quite helpful.

Otherwise if it can't be helped you may have to point users to a guide on how to compile the launcher themselves.

**Comment by OSA413** [comment]
> how they created the binary

Here's the instruction to build it:
```
sudo apt install gcc-mingw-w64-i686 g++-mingw-w64-i686
git clone https://github.com/darealshinji/sonic-4-launcher
cd ./sonic-4-launcher
git submodule init && git submodule update
make
```
The binary mentioned in [the first comment](https://github.com/darealshinji/sonic-4-launcher/issues/1#issuecomment-616274164)  was built on Ubuntu 16.04. The others were compiled on Xubuntu 18.04 and they have the same size as the r3's binary.

No code changes were made.

**Comment by darealshinji** [comment]
The binary provided by icup321 was 1.7 M uncompressed, the r3 binary is ~900k. Must be some version differences in the mingw packages I guess. Anyway, I guess as long as one of the builds doesn't false-positive trigger Windows Defender it's fine.
