### ISSUE TITLE
Add support for resolutions higher than 1920x1080

### ISSUE THREAD

**Issue by icup321** [darealshinji/sonic-4-launcher#2]
So I did an examination on the original Java launcher for Sonic 4 - Episode 1 and it turns out the resolution options are NOT hard-coded, which means it is possible to play it at higher resolutions like 1440p or 4K. However, looking at the code, it seems you chose to hard-code the resolution options to a maximum of 1080p:
https://github.com/darealshinji/sonic-4-launcher/blob/master/src/configuration.cpp

My question is whether or not it would be possible for you to code in a way for your launcher to detect all available 16:9 resolutions based on the current monitor being used. I know this might be something difficult to implement, and sadly I don't have that much experience in coding, so I don't know how exactly I could implement this. If you or anyone else would be willing to implement this though that would be great since it is definitely possible to play Sonic 4 at 4K natively using a fixed executable (despite it saying it only upscales it to 1080p, it does indeed work for higher resolutions): https://community.pcgamingwiki.com/files/file/584-sonic-the-hedgehog-4-episode-i-1080p-fix/

**Comment by darealshinji** [comment]
I will take a look at it.

**Comment by darealshinji** [comment]
The resolutions are now aquired dynamically from the system.
I may still have to take a look at this part: https://github.com/darealshinji/sonic-4-launcher/commit/8d6d5b1160a9f46ee0898279e2a7e4e278712206#diff-6df0f44e869bb35e4037a237c8c24929R349

**Comment by icup321** [comment]
I just compiled the executable and that recent commit seemed to do the trick! It's working perfectly for me now, I can finally select 2560x1440 which my monitor supports: 
![Untitled](https://user-images.githubusercontent.com/28464642/80214088-36794900-8608-11ea-998f-fc4c63262b2d.png)

Are you planning on making any more code changes soon, or should I just go ahead and close the issue? (I know you said you want to look into something, but it seems to be working fine for me.)

**Comment by darealshinji** [comment]
I'm closing it, since the resolution issue is solved. I will take a closer look into supporting multiple monitors, but that shouldn't take too long.
